name: video_timeline
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=23.0.0
  # Core ML
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.7  # Change based on your CUDA version
  - numpy>=1.23.0
  # Scientific
  - scipy>=1.10.0
  - pandas>=2.0.0
  - scikit-learn>=1.2.0
  # Video/Audio Processing
  - ffmpeg>=4.0  # System ffmpeg
  - librosa>=0.10.0
  # UI (Desktop)
  - pyqt>=5.15.9
  # Database
  - sqlalchemy>=2.0.0
  # Development
  - black>=23.3.0
  - pytest>=7.3.1
  - pip:
    # Scene Detection 
    - scenedetect>=0.6.1
    # Audio/Video
    - moviepy>=1.0.3
    - ffmpeg-python>=0.2.0
    - openai-whisper>=20230314
    - pyaudioanalysis>=0.3.14
    # Computer Vision
    - opencv-python>=4.7.0
    - deepface>=0.0.79
    - albumentations>=1.3.0
    # Deep Learning
    - transformers>=4.28.0
    - datasets>=2.10.0
    - open_clip_torch>=2.20.0
    - sentence-transformers>=2.2.2
    - timm>=0.9.2
    - bitsandbytes>=0.39.0
    - accelerate>=0.19.0
    - diffusers>=0.16.0
    # Vector Search
    - faiss-cpu>=1.7.0  # Use faiss-gpu for GPU version
    - chromadb>=0.4.0
    # Web UI
    - fastapi>=0.95.0
    - uvicorn>=0.22.0
    - jinja2>=3.1.2
    - aiofiles>=23.1.0
    # Utilities
    - tqdm>=4.65.0
    - pydantic>=2.0.0
    - imageio>=2.27.0
    - python-multipart>=0.0.6
    # Testing
    - pytest-cov>=4.1.0
    - mypy>=1.2.0
    - flake8>=6.0.0
    - isort>=5.12.0